version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: io.micrometer:micrometer-registry-prometheus
    versions:
    - 1.6.4
    - 1.6.5
  - dependency-name: io.projectreactor:reactor-core
    versions:
    - 3.4.3
    - 3.4.4
  - dependency-name: io.projectreactor:reactor-test
    versions:
    - 3.4.2
    - 3.4.3
    - 3.4.4
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.8.0
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.2
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
